# Generated by Django 5.0.6 on 2024-06-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='detalle_venta',
        ),
        migrations.AddField(
            model_name='venta',
            name='detalle_venta',
            field=models.ManyToManyField(to='web.detalleventa'),
        ),
    ]
